### ISSUE TITLE
Check for gpstime order always true.

### ISSUE THREAD

**Issue by Jean-Romain** [hobuinc/copc-validator#1]
I uploaded [2 identical copc files](https://drive.google.com/file/d/1DVnqFPkaaaNXYOKemCFURGRWFxN-M6LX/view?usp=sharing) into the **online copc validator**. The first one has its points sorted by gpstime, the second one has its point in a random order (per node). For both the validator says that points are properly sorted (with deep scan). So it seems that the gpstime order test always returns `true`.

**Comment by hobu** [comment]
🐛  reported to @TheMrCam and he's on it.

**Comment by TheMrCam** [comment]
Good catch, thank you for reporting! Finally closing now that [validate.copc.io](https://validate.copc.io) has the fix deployed. Let us know if you find any other issues!
